name: CI (pull request)

on:
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: setup rust toolchain
        run: rustup update && rustup toolchain install
      - uses: taiki-e/install-action@v2
        with:
          tool: nextest
      - uses: taiki-e/install-action@v2
        with:
          tool: mdbook
      - uses: taiki-e/install-action@v2
        with:
          tool: mdbook-toc
      - name: install sitemap generator
        run: npm install --global static-sitemap-cli@2.2.7
      - name: check and build
        run: cargo x ci
      - name: check sitemap
        run: mini-lsm-book/sitemap.sh --check
